# This is an example OpenAPI specification
# It illustrates a dependency of the Petstore OpenDep specification.
---
openapi: "3.0.1"

info:
  title: Sample Petstore order service
  description: This is a sample OpenAPI specification describing a service for ordering pet supplies.
  contact:
    name: Pete Cornish
    url: https://github.com/opendeps
    email: opendeps@example.com
  version: "1.0.0"

paths:
  /supplies:
    get:
      security:
        - BasicAuth: []
      responses:
        '200':
          description: Lists supplies for sale
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                    - price
                  properties:
                      name:
                        type: string
                      price:
                        type: number
                        format: double
              examples:
                itemsExample:
                  value:
                    [
                      { "name": "Food bowl", "price": 3.99 },
                      { "name": "Brush", "price": 2.99 }
                    ]

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
